/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_opsunv_mt4_api_MT4 */

#ifndef _Included_com_opsunv_mt4_api_MT4
#define _Included_com_opsunv_mt4_api_MT4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_opsunv_mt4_api_MT4
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_opsunv_mt4_api_MT4_init
  (JNIEnv *, jobject);

/*
 * Class:     com_opsunv_mt4_api_MT4
 * Method:    Release
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_opsunv_mt4_api_MT4_Release
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_opsunv_mt4_api_MT4
 * Method:    ErrorDescription
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_opsunv_mt4_api_MT4_ErrorDescription
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_opsunv_mt4_api_MT4
 * Method:    Connect
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_opsunv_mt4_api_MT4_Connect
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_opsunv_mt4_api_MT4
 * Method:    Disconnect
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_opsunv_mt4_api_MT4_Disconnect
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_opsunv_mt4_api_MT4
 * Method:    IsConnected
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_opsunv_mt4_api_MT4_IsConnected
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_opsunv_mt4_api_MT4
 * Method:    Login
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_opsunv_mt4_api_MT4_Login
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     com_opsunv_mt4_api_MT4
 * Method:    TradesRequest
 * Signature: (I)[Lcom/opsunv/mt4/api/bean/TradeRecord;
 */
JNIEXPORT jobjectArray JNICALL Java_com_opsunv_mt4_api_MT4_TradesRequest
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_opsunv_mt4_api_MT4
 * Method:    TradesUserHistory
 * Signature: (I)[Lcom/opsunv/mt4/api/bean/TradeRecord;
 */
JNIEXPORT jobjectArray JNICALL Java_com_opsunv_mt4_api_MT4_TradesUserHistory
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_opsunv_mt4_api_MT4
 * Method:    WinsockStartup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_opsunv_mt4_api_MT4_WinsockStartup
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
